services:
  app:
    build:
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./server/src/main:/app/src/main
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      dockerfile: Dockerfile-dev
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  db:
    ports:
      - "5432:5432"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
