services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    expose:
      - "6379"  

  app:
    build:
      context: ./server
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${APP_PROFILES_ACTIVE}
      SPRING_DATA_REDIS_HOST: ${CACHE_HOST}
      SPRING_DATA_REDIS_PORT: ${CACHE_PORT}
      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_PORT: ${MAIL_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      OCI_CONFIG_PATH: /.oci/config
    volumes:
      - /home/ubuntu/.oci:/.oci

  web:
    build:
      context: ./web
    ports:
      - "443:443" # Usado apenas em produção, pois em testes automatizados utilizado na rede interna.
    depends_on:
      - app  

volumes:
  redis_data:

