spring:
  application:
    name: trackroom
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  threads:
    virtual:
      enabled: true

logging:
  level:
    org.springframework.security: DEBUG

server:
  servlet:
    context-path: /api
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  key: a9c986ede938a8b4f8721737c62efd8568ba43e976e2b77cdd90d0b2c4f66e97
  accessTokenExpiration: 3600

filestorage:
  endpoint: https://objectstorage.sa-saopaulo-1.oraclecloud.com

queue:
  ids:
    email-account-confirmation-id: 'ocid1.queue.oc1.sa-saopaulo-1.amaaaaaawchok4iamlvh4y2dv6bzl23vnokzike6vhynakjgipaikqbzle4q'