FROM eclipse-temurin:21-jdk-jammy AS development

WORKDIR /app

COPY . /app

EXPOSE 8080

ARG CLOUD=local
ENV SPRING_PROFILES_ACTIVE=$CLOUD

# Fetch project dependencies
RUN chmod +x start.sh && ./gradlew getDependencies

# script which watches source file changes in background and executes bootRun
CMD ["sh", "start.sh"]