FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app

ARG CLOUD=local
ENV SPRING_PROFILES_ACTIVE=$CLOUD

COPY gradlew build.gradle.kts settings.gradle.kts start.sh ./
COPY gradle/ gradle/

COPY core/ core/
COPY queue/ queue/
COPY storage/ storage/

RUN chmod +x gradlew start.sh \
    && ./gradlew dependencies \
        --configuration runtimeClasspath \
        -Pcloud=$CLOUD \
        --no-daemon

EXPOSE 8080 5005

CMD ["sh", "start.sh"]