name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

env:
  RESOURCE_GROUP: trackroom-app
  CONTAINER_APP_NAME: trackroomback
  ACR_NAME: trackroomreg
  IMAGE_NAME: trackroom-api
  IMAGE_TAG: ${{ github.sha }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      front: ${{ steps.filter.outputs.front }}
      back: ${{ steps.filter.outputs.back }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            front:
              - 'web/**'
            back:
              - 'server/**'
              
  frontend-tests:
    needs: changes
    if: |
      (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')) &&
      needs.changes.outputs.front == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25' # Or any other version compatible with your project
          cache: 'npm' # Caches dependencies

      - name: Install dependencies
        run: cd web && npm ci # Use 'npm ci' for clean and fast installs in CI environments

      - name: Execute Vitest tests
        run: cd web && npm run test # Runs the 'test' script in package.json              

  build_and_deploy_front:
    needs: frontend-tests
    if: |
      (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')) &&
      needs.changes.outputs.front == 'true'
    runs-on: ubuntu-latest
    name: Build and Deploy Front
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_POND_0C4FB600F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./web"
          api_location: ""
          output_location: "dist"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_POND_0C4FB600F }}
          action: "close"

#  backend-tests:
#    runs-on: ubuntu-latest
#    needs: changes
#    if: github.event_name == 'push' && needs.changes.outputs.back == 'true'
#    steps:
#    - uses: actions/checkout@v4

#    - name: Set up JDK 21
#      uses: actions/setup-java@v4
#      with:
#        java-version: '21'
#        distribution: 'temurin'
#        cache: gradle

#    - name: Setup Gradle
#      uses: gradle/actions/setup-gradle@v3

#    - name: Grant execute permission for gradlew
#      run: cd server && chmod +x gradlew

#    - name: Run Gradle tests
#      run: cd server && ./gradlew test --stacktrace
  
  build_and_deploy_back:
    needs: changes
    if: github.event_name == 'push' && needs.changes.outputs.back == 'true'
    runs-on: ubuntu-latest
    environment: azure_prod
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: az acr login --name $ACR_NAME

      - name: Build Docker image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG -f server/Dockerfile --build-arg CLOUD=azure ./server

      - name: Push Docker image
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG

      - name: Deploy new revision to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          imageToDeploy: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
