name: Run Docker Compose Commands

on:
  push:
    branches:
      - master

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25' # Or any other version compatible with your project
          cache: 'npm' # Caches dependencies

      - name: Install dependencies
        run: cd web && npm ci # Use 'npm ci' for clean and fast installs in CI environments

      - name: Execute Vitest tests
        run: cd web && npm run test # Runs the 'test' script in package.json

  build-and-deploy-front:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '25'

    - name: Install dependencies and build React app
      run: |
        cd web
        npm install
        npm run build
      env:
        # Optional: Set environment variables for React app if needed (e.g., CI=false to avoid warnings as errors)
        CI: false

    - name: Debug Folder Structure
      run: ls -R web/dist
      
    - name: Sync build files to OCI Object Storage
      uses: oracle-actions/run-oci-cli-command@v1.3.2
      run: |
          oci os object bulk-upload --bn ${{ secrets.OCI_BUCKET_NAME }} --ns ${{ secrets.OCI_NAMESPACE }} --src-dir web/dist --overwrite
          find dist -name "*.svg" | while read f; do oci os object put --ns ${{ secrets.OCI_NAMESPACE }} --bn ${{ secrets.OCI_BUCKET_NAME }} --name "${f#web/dist/}" --file "$f" --content-type "image/svg+xml" --force; done
          find dist -name "*.css" | while read f; do oci os object put --ns ${{ secrets.OCI_NAMESPACE }} --bn ${{ secrets.OCI_BUCKET_NAME }} --name "${f#web/dist/}" --file "$f" --content-type "text/css" --force; done
          find dist -name "*.js" | while read f; do oci os object put --ns ${{ secrets.OCI_NAMESPACE }} --bn ${{ secrets.OCI_BUCKET_NAME }} --name "${f#web/dist/}" --file "$f" --content-type "application/javascript" --force; done
          find dist -name "*.webmanifest" | while read f; do oci os object put --ns ${{ secrets.OCI_NAMESPACE }} --bn ${{ secrets.OCI_BUCKET_NAME }} --name "${f#web/dist/}" --file "$f" --content-type "text/webmanifest" --force; done
          find dist -name "*.png" | while read f; do oci os object put --ns ${{ secrets.OCI_NAMESPACE }} --bn ${{ secrets.OCI_BUCKET_NAME }} --name "${f#web/dist/}" --file "$f" --content-type "image/png" --force; done
          oci os object put --ns ${{ secrets.OCI_NAMESPACE }} --bn ${{ secrets.OCI_BUCKET_NAME }} --name index.html --file web/dist/index.html  --content-type "text/html; charset=utf-8" --force
      env:
        OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
        OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
        OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
        OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
        OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        # Set silent to false for debugging if necessary, but true is recommended for security
        SILENT: false    
  
  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Grant execute permission for gradlew
      run: cd server && chmod +x gradlew

    - name: Run Gradle tests
      run: cd server && ./gradlew test --stacktrace
  
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    env:
      APP_PROFILES_ACTIVE: ${{ secrets.APP_PROFILES_ACTIVE }}
      CACHE_HOST: ${{ secrets.CACHE_HOST }}
      CACHE_PORT: ${{ secrets.CACHE_PORT }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      APP_FRONT_URL: ${{ secrets.APP_FRONT_URL }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt install python3-paramiko
        sudo apt-get install -y docker-compose
      
    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.ENVIRONMENT_HOST }} >> ~/.ssh/known_hosts

    - name: Execute Docker Compose Down
      run: |
        DOCKER_HOST=ssh://${{ secrets.SSH_USER }}@${{ secrets.ENVIRONMENT_HOST }} docker compose stop app
        DOCKER_HOST=ssh://${{ secrets.SSH_USER }}@${{ secrets.ENVIRONMENT_HOST }} docker compose rm -f app        

    - name: Execute Docker Compose Up
      run: |
        DOCKER_HOST=ssh://${{ secrets.SSH_USER }}@${{ secrets.ENVIRONMENT_HOST }} docker compose build --pull app
        DOCKER_HOST=ssh://${{ secrets.SSH_USER }}@${{ secrets.ENVIRONMENT_HOST }} docker compose up -d app
