FROM node:25.0-slim AS development

WORKDIR /app

# dependências básicas
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci --legacy-peer-deps

CMD ["npx", "vite", "--host", "0.0.0.0"]
